version: "2"
checks:
  argument-count:
    enabled: true
  method-complexity:
    enabled: true
  method-count:
    enabled: true
  file-lines:
    enabled: true

engines:
  eslint:
    enabled: false
  fixme:
    enabled: true
  duplication:
    enabled: true
  radon:
    enabled: true

ratings:
  paths:
    - "**.py"

exclude_paths:
  - "tests/"